### PR TITLE
Add clusterResourceOverridesEnabled to config.js

### PR DESCRIPTION
**Pull request by spadgett**
Bumps dependencies to pick up https://github.com/openshift/api/pull/32

/assign @deads2k 
/cc @jwforres

### CODE REVIEW

**Comment by jwforres** [comment]
Lgtm but Jenkins failed

**Comment by spadgett** [comment]
/test check

@deads2k did you want to look at this one since I bumped dependencies?

**Comment by spadgett** [comment]
@jwforres Looks like we have a flake where the check job sometimes fails :(

**Comment by spadgett** [comment]
Replaced by #25

**Pull request closed without merging**
