### PR TITLE
remove weird origin dependency

### PR DESCRIPTION
**Pull request by deads2k**
This looks like weird copy/paste problem.

@smarterclayton @spadgett @bparees

### CODE REVIEW

**Comment by smarterclayton** [comment]
This is a bug in the hack clone script - it's supposed to change the import statements but doesn't.  For now, if this isn't using golang unit, you can delete it.  I have a branch that fixes it but I won't get there.

**Comment by smarterclayton** [comment]
Are there go units in this repo?

**Comment by deads2k** [comment]
> Are there go units in this repo?

I don't know what a go unit is.  We have golang code, but I'm snipping the last few origin links.

**Comment by smarterclayton** [comment]
Go based unit tests that must be run in order for this repo to pass CI tests, in which case it needs to generate unit reports, in which case it needs junit parser.

**Comment by deads2k** [comment]
> Go based unit tests that must be run in order for this repo to pass CI tests, in which case it needs to generate unit reports, in which case it needs junit parser.

Yes, we have golang unit tests.  The simple sed seems to have worked here.

**Pull request merged**
