### PR TITLE
Copy over hack scripts so that vendoring will work

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
This is a direct copy of the hack scripts from origin used during build processes including console vendoring. `hack/vendor-console.sh` script works fine with these in place

**Comment by spadgett** [comment]
If we wanted to, I suspect we could remove the dependency on the other scripts with some small changes to `vendor-console.sh`. We might need the other scripts for RPM builds anyway, though. See https://github.com/openshift/image-registry/pull/6

I think @smarterclayton had an rsync solution for keeping the hack scripts in sync across repos.

cc @stevekuznetsov

**Comment by jwforres** [comment]
Yeah I assumed we will need them for the builds anyway

**Comment by stevekuznetsov** [comment]
Yeah we should populate these from `openshift/release` with the `rsync` tool [here](https://github.com/openshift/release/blob/master/tools/hack/golang/update)

**Comment by spadgett** [comment]
Looks like #6 has most of the same hack scripts after running the rsync tool, although not the vendor script.

**Comment by jwforres** [comment]
i just copied the vendor script verbatim, didnt require any changes, if you just want to add that to #6 we can close this one

**Comment by stevekuznetsov** [comment]
@openshift-ci-robot I'm not going to tell you again

/close

**Pull request closed without merging**
