### PR TITLE
freedom!

### PR DESCRIPTION
**Pull request by deads2k**
Snip the links to origin and k8s.io/kubernetes to reduce the glide import tree and simplify everything

/assign spadgett

### CODE REVIEW

**Comment by deads2k** [comment]
10 million lines removed, you've got to merge it, right? :)

**Comment by deads2k** [comment]
@stevekuznetsov we need a bigger flag

**Comment by stevekuznetsov** [comment]
oh no

**Comment by spadgett** [comment]
I had a couple comments from #15, but I can look at those as a follow on.

**Comment by spadgett** [comment]
We'll have to coordinate this with cluster up and install changes since it requires a different asset config version.

cc @sdodson @jwforres

**Comment by spadgett** [comment]
@deads2k Is there any not-terrible way to accept `apiVersion: v1` as `webconsole.config.openshift.io/v1` until we can make the install and cluster up changes? I'm not sure how we coordinate this otherwise without there being a window where it's broken.

**Comment by deads2k** [comment]
> @deads2k Is there any not-terrible way to accept apiVersion: v1 as webconsole.config.openshift.io/v1 until we can make the install and cluster up changes? I'm not sure how we coordinate this otherwise without there being a window where it's broken.

Maybe.  Do you have a place to test it?

**Comment by spadgett** [comment]
You should be able to test with cluster up.

**Comment by spadgett** [comment]
I can test it for you too if that helps

**Comment by deads2k** [comment]
> You should be able to test with cluster up.

I tried building the images before and it failed.

Updated with a commit that attempts to cross-register for decoding.

**Comment by spadgett** [comment]
Closer. Different error now:

> Error: no kind "WebConsoleConfiguration" is registered for the internal version of group "webconsole.config.openshift.io"

**Review by spadgett — APPROVED** [review]

**Comment by spadgett** [comment]
Here goes nothing...

/lgtm

**Pull request merged**
