### PR TITLE
create container.yaml for odcs multi-arch build

### PR DESCRIPTION
**Pull request by jeffdyoung**
create container.yaml for odcs multi-arch build
@dorzel @adammhaile Please review.

### CODE REVIEW

**Comment by adammhaile** [comment]
+1

**Comment by dorzel** [comment]
+1

**Comment by spadgett** [comment]
Do we need this change in enterprise-3.9 and enterprise-3.11?

**Comment by adammhaile** [comment]
Eventually, in all branches.

**Comment by spadgett** [comment]
Tagging based on reviews from @adammhaile and @dorzel 

/lgtm

**Pull request merged**
