### PR TITLE
Set Referrer-Policy to a stricter level than the browser default

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1504571

### CODE REVIEW

**Comment by jwforres** [comment]
oh right, supposed to use that
/assign @spadgett 
thing

**Review by spadgett — APPROVED** [review]

**Comment by jwforres** [comment]
🎉  merge works @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Nice!

**Pull request merged**
