### PR TITLE
Validate extension scripts and stylesheets as URLs

### PR DESCRIPTION
**Pull request by spadgett**
Also remove validation of obsolete extensions directories array, which is no longer used.

The extension property names will be updated in a follow-on.

/assign @jwforres 
/cc @deads2k

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM not sure if you were wanting @deads2k to review it ?

**Comment by spadgett** [comment]
Not necessarily. It's a small change if you're good with it.

**Comment by deads2k** [comment]
@spadgett Are you going to put something together tweaking the API struct in openshift/api to match what you want or would you like me to?

**Comment by spadgett** [comment]
@deads2k I was going to, but I don't know the process for it.

**Pull request merged**
